### ISSUE TITLE
getJSONWithCache is broken

### ISSUE THREAD

**Issue by leonard84** [Transmogrify-for-Plex/Transmogrify-for-Plex-firefox#9]
In 
https://github.com/Transmogrify-for-Plex/Transmogrify-for-Plex-firefox/blob/aaa9eafa936e7bee18e2a8cdf1c034128e21e2bd/data/utils.js#L221
the function `getJSONWithCache` does not forward the custom_headers correctly they get passed to `cache_get` which doesn't need/use them and not to the nested `getJSON` call which actually needs them.

**Comment by leonard84** [comment]
@Moussa could you please fix this, this breaks pretty much everything. If you want I can create a PR.

**Comment by Moussa** [comment]
@leonard84 Please do create a PR as I no longer actively maintain this extension

**Comment by leonard84** [comment]
@Moussa the Chrome version does not have this bug

**Comment by leonard84** [comment]
I created PR #10 to fix it

**Comment by leonard84** [comment]
@Moussa thanks for the quick response, did you submit it to Mozilla? I've seen that you bumped the version and updated the changelist already.

**Comment by Moussa** [comment]
@leonard84 Its already been submitted and should land in a couple of days.

**Comment by leonard84** [comment]
thx looking forward to having a working version again
